### ISSUE TITLE
allineamento dati

### ISSUE THREAD

**Issue by aleairaghi** [stuffcube/ARI_V3#2]
una volta modificato il sottomodulo come si allinea la versione completa? ho cancellato il software non piu usato nel sottomodulo software ora vorrei propagare la modifca in quello completo

**Comment by stuffcube** [comment]
Dal repository padre devi fare:
- `git add 01_pcSoftware` indicando solo la directory del sottomodulo che vuoi aggiornare
- `git commit -m "update submodule -> 01_pcSoftware"' o qualche cosa del genere
- infine `git push origin master`
