### ISSUE TITLE
interruttore fisico per cancellare parametri di rete

### ISSUE THREAD

**Issue by aleairaghi** [stuffcube/ARI_V3#4]
se si sbaglia qualcosa altrimenti si è costretti a spegnere il router o ricaricare il firmware :-(

**Comment by giorgio323323** [comment]
inserito nella versione:
  10mar19 1.00.05
  reset configurazione WiFi con pin D3

premendolo viene cancellata la configurazione.  Occorre spegnere e accendere nuovamente
