### ISSUE TITLE
gestione scelta velocita nelle varie modalita di run

### ISSUE THREAD

**Issue by aleairaghi** [stuffcube/ARI_V3#5]
nel mio caso le inpostazini di pwm predefinite danno qualche problema

**Comment by giorgio323323** [comment]
con il comando "V" puoi modificarla. Valori da 0 a 255.
      case 'V':
          motorSpeedValue = x;
          risposta = "V: " + String(motorSpeedValue);
        break;

**Comment by aleairaghi** [comment]
Ad esempio qui motorSpeedRef =  108; andrebbe messo variabile

**Comment by stuffcube** [comment]
Questo issue puo' essere chiuso?

**Comment by aleairaghi** [comment]
andrebbero gestite le varie velocità secondo me  (tipo motorSpeedRef)  ma direi che la priorità è bassa. posssiamo anche chiuderla per adesso e verificare quando ci saranno più arianne attive, magari è solo un mio problema
