### ISSUE TITLE
esp va in reset continuo

### ISSUE THREAD

**Issue by stuffcube** [stuffcube/ARI_V3#9]
test case:
primo caricamento FW. Esp non riconosce la rete e si mette in modo access poin.
inserisco ssid e psw.
non inserisco nome robot e numero porta (i valori rimangono ombreggiati)
salvo.

a questo punto l'esp continua ad andare in errore di wdt e si resetta continuamente.
vedi dump da seriale.

per uscirne va ricaricato il FW

**Comment by aleairaghi** [comment]
ho provato ma mi usa i parametri salvati la volta precedente ora ho fatto questi passi 
1)esptool.py --port com9 flash_id
esptool.py v2.3.1
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Uploading stub...
Running stub...
Stub running...
Chip ID: 0x000edb65
Hard resetting via RTS pin...

esptool.py v2.3.1
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Uploading stub...
Running stub...
Stub running...
Manufacturer: c8
Device: 4016
Detected flash size: 4MB
Hard resetting via RTS pin...

cancallato la flash
esptool.py --port comx erase_flash
e caricato il firmware:
nodemcu-master-7-modules-2019-02-04-09-08-18-float.bin

ripartiamo tutti da questo stato (anche se il modello di esp non è uguale  non importa ma almeno allineiamo il firmware)

**Comment by aleairaghi** [comment]
aggiungere default a parametri
char* nomeari="arianna";
char* portAri="9500";

risolve parzialmente il problema. In ogni caso serve la possibilita di resettare in qualche modo la configurazione eventualmente anche software. giorgio modifichi tu il firmware ciao
